### PR TITLE
error pop-up fixed

### LINKED ISSUE #301: [Bug] Redundant pop-up when Email already taken
## Describe the bug

- While creating a new user with a previously registered email, the error message shows `Email already taken` along with a pop-up as follows, for a short time:
- The pop-up error message should be removed or updated as that information is redundant to the end-user and affects the UX.

image

## To Reproduce

1. Register an account with any email.
2. Try creating a new user with the same email used before
3. Then the error pop-up appears

## Expected behavior

- There should either be no pop-up in this case as the error message showing `Email already exists` is already there or the pop-up text should be changed to the same text as it will be short lived.

## Logs

image

## Environment:

- OS: Windows 10
- Browser: Chrome

### PR DESCRIPTION
**Pull request by gurpreet-legend**
**Issue Number**

fixes #301 

**Describe the changes you've made**

I have removed the `toast` error pop-up from `Register.js` component

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

https://github.com/EOS-uiux-Solutions/user-story/blob/main/src/pages/Register.js#L56

### CODE REVIEW

**Comment by gurpreet-legend** [comment]
Please review this!

File: src/pages/Register.js [hunk 1]
```diff
@@ -53,7 +53,6 @@ export const Register = () => {
       navigate('/', { replace: true })
     } catch (e) {
       console.error(e.message)
-      toast.error(e.message)
```
Comment (kailash360) [inline src/pages/Register.js:56]: The toast should should not be removed from the page in this way. We should display the error message associated with the sign-up so that the user can understand what is the issue.

Comment (gurpreet-legend) [reply src/pages/Register.js:56]: Actually, the error message is already been indicated on the sign-up page, if you follow the instructions I have given for replicating the bug, you'll find out there's one error indication of `Email exist` and also a toast pops up with `data is undefined` text, so I only removed the toast not the actual error message getting displayed.

Comment (kailash360) [reply src/pages/Register.js:56]: Got it
