### PR TITLE
Fixed build fail due to warnings

### LINKED ISSUE #120: Fix build fail due to warnings
## Describe the bug

Currently, the build is failing because the react-build generates warnings, and these warnings are treated as error by the servers.

## To Reproduce

1. Ru the command
```sh
npm run build
```
2. The build is successful but the warnings are generated in the process.

## Expected behavior

It is expected that the build process is completed successfully without generating any warnings. This will also prevent the current deployment fails.

### PR DESCRIPTION
**Pull request by kailash360**
**Issue Number**

fixes #120 

**Describe the changes you've made**

I have made the following 3 changes to prevent any warnings while generating the build.
- Provided a name to the component used as footer
- Fixed `react-hooks/exhaustive-deps warning` by fixing the use of useEffect hook
- Added a `useMemo` hook to fix the state management while re-rendering

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Additional context (OPTIONAL)**

NA

**Test plan (OPTIONAL)**

1. Run the command 
```js
npm run build
```
2. The build is completed successfully without any warnings

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

image

### CODE REVIEW

File: src/modules/TitleSearch.js [hunk 1]
```diff
@@ -9,20 +8,14 @@ const Search = (props) => {
...
-  )
-
-  useEffect(() => {
-    if (!title) {
-      return
-    }
-    handleTitleChange(title)
-  }, [title, handleTitleChange])
+    }, 600)
+  }, [title])
```
Comment (Abhirup-99) [inline src/modules/TitleSearch.js:18]: why this change?

Comment (kailash360) [reply src/modules/TitleSearch.js:18]: Also @Abhirup-99 , 
as per the discussion [here](https://github.com/facebook/react/issues/19240), they asked to use `useMemo` hook. But for the latest versions, the same warning was generated. Hence the said change was asked to be made.
