### PR TITLE
Fix #147: All stories are displayed by default

### LINKED ISSUE #147: [Bug] Show all stories by default
## Describe the bug

Currently, the stories in the homepage of the application are of `Under Consideration` status, by default. 
It does not show all the stories in one go.

## To Reproduce

1. Open https://userstory.eosdesignsystem.com/
2. Scroll down to list of stories
3. All stories are of `Under Consideration` type by default

## Expected behavior

Initially, all the stories in the database should be shown to the user. 
If the user applies any filter, it should change the list accordingly.

## Environment (please complete the following information):

- OS: Windows 10
- Browser: Chrome

## Additional context

For more details, refer to [UX issue: Show all stories first](https://userstory.eosdesignsystem.com/story/60e594767d64b00015dc255e) by @cyntss

### PR DESCRIPTION
**Pull request by kailash360**
**Issue Number**

fixes #147 

**Describe the changes you've made**

I have added a new element in the `StatusList` i.e `All` to represent the status of displaying all the stories. I have also used ternary operator to dynamically modify the service which is made to fetch the stories. This will help to fetch all the stories, irrespective of the status.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Additional context (OPTIONAL)**

NA

**Test plan (OPTIONAL)**

NA

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

https://user-images.githubusercontent.com/75155230/156059503-3b015bd3-a60e-457c-b9cd-a1d2c913821f.mp4

### CODE REVIEW

File: src/components/Stories.js [hunk 1]
```diff
@@ -12,13 +12,13 @@ import userStory from '../services/user_story'
 import ProductList from './ProductList'
 
 const Stories = ({ authorId, followerId }) => {
-  const [currentStateSelected, selectState] = useState('Under consideration')
+  const [currentStateSelected, selectState] = useState('All')
```
Comment (kbhutani0001) [inline src/components/Stories.js:15]: can we make enum for this instead of string?

Comment (kailash360) [reply src/components/Stories.js:15]: All the status are already declared in a separate [List](https://github.com/EOS-uiux-Solutions/user-story/blob/main/src/utils/Lists.js#L11) inside the `utils` sub-directory. It behaves like a constant there. Perhaps, instead of the string, I can use `useState(List[0].status)` to use the first element of the list of status i.e `All`.
Should I implement this approach?
